import cn from '@/utils/classNames'
import type { Metadata } from 'next'
import { ThemeProvider } from 'next-themes'
import { Josefin_Sans } from 'next/font/google'
import { PropsWithChildren } from 'react'
import './globals.css'

const josefinSans = Josefin_Sans({
  subsets: ['latin'],
  weight: ['400', '700'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn('antialiased', josefinSans)}>
        <ThemeProvider attribute="class">{children}</ThemeProvider>
      </body>
    </html>
  )
}
